### PR TITLE
Do not use ABSL_HAVE_EXCEPTIONS.

### LINKED ISSUE #254: Remove usage of ABSL_HAVE_EXCEPTIONS
For the background as to why we need to remove Abseil, check #232.  Create a new macro (`GOOGLE_CLOUD_CPP_HAVE_EXCEPTIONS` ?).

### PR DESCRIPTION
**Pull request by coryan**
Created new macro (GOOGLE_CLOUD_CPP_HAVE_EXCEPTIONS), use that
instead, this fixes #254.

### CODE REVIEW

File: bigtable/client/internal/port_platform.h [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+#error "Bigtable C++ Client requires C++11, your version of MSVC is too old"
+#endif  // _MSC_VER
+
+// With Microsoft Visual Studio we need an extra header for the word boolean
+// operators.
+#include <ciso646>
+
+// Discover if exceptions are enabled and define them as needed.
+#ifdef GOOGLE_CLOUD_CPP_HAVE_EXCEPTIONS
+#error GOOGLE_CLOUD_CPP_HAVE_EXCEPTIONS should not be directly set.
```
Comment (mbrukman) [inline bigtable/client/internal/port_platform.h]: Would it make sense to keep the `#` flush left, but indent everything after it to show the `ifdef` / `else` / `endif` blocks for readability? I'm having trouble seeing what's inside which block, since there are no curly braces, and no indentation to explain what's going on.

E.g.,

```cpp
#ifdef
#  if defined(...)
    // stuff here
#  else
    // something else here
#  endif
#else
#endif
```

Comment (coryan) [reply bigtable/client/internal/port_platform.h]: Good idea.  Done.

File: bigtable/client/internal/readrowsparser_acceptance_tests.inc [hunk 2]
```diff
@@ -454,7 +454,7 @@ TEST_F(AcceptanceTest, SplitCellBareCommit) {
           qualifier: < value: "C">
           timestamp_micros: 100
           value: "v"
-          value_size: 10
```
Comment (mbrukman) [inline bigtable/client/internal/readrowsparser_acceptance_tests.inc]: What are all the numeric changes? Are they necessary? For testing? To force test re-runs?

Comment (coryan) [reply bigtable/client/internal/readrowsparser_acceptance_tests.inc]: Good find... I regenerated the file using the [script](https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/master/bigtable/tools/convert_acceptance_tests.py), which downloads this [file](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/commits/master/bigtable-client-core-parent/bigtable-client-core/src/test/resources/com/google/cloud/bigtable/grpc/scanner/read-rows-acceptance-test.json) as its source data.  And evidently the file changed in the last couple of days.

Comment (coryan) [reply bigtable/client/internal/readrowsparser_acceptance_tests.inc]: I should have added: that means I do not know what the changes are for, I am sure there is a good reason for them, but as long as the tests exercise the code and they pass, I am Okay with whatever values we want there.

Comment (mbrukman) [reply bigtable/client/internal/readrowsparser_acceptance_tests.inc]: Welll, in that case...

image

File: bigtable/client/internal/port_platform.h (hunk 1 above)
Comment (coryan) [reply bigtable/client/internal/port_platform.h]: Aaaand `clang-format` does not like that.  Bummer.  Thoughts?  I am inclined to do whatever `clang-format` wants.

Comment (mbrukman) [reply bigtable/client/internal/port_platform.h]: See https://clang.llvm.org/docs/ClangFormatStyleOptions.html; specifically:

> ### IndentPPDirectives (PPDirectiveIndentStyle)

You want the option:

> PPDIS_AfterHash (in configuration: AfterHash) Indents directives after the hash.

Comment (coryan) [reply bigtable/client/internal/port_platform.h]: Unfortunately that is a very recent addition to clang-format.  It is not in the version we use:

* http://releases.llvm.org/4.0.1/tools/clang/ClangFormatStyleOptions.html

Nor in 5.0:

* http://releases.llvm.org/5.0.1/tools/clang/docs/ClangFormatStyleOptions.html

and both of those are newer than whatever is distributed with Ubuntu 16.04 and 14.04.

I have turned off clang-format in this section of the code.  It is sufficiently special that I think that makes the most sense.
