### PR TITLE
Troubleshoot bug 1087

### LINKED ISSUE #1087: Link both bigtable and storage clients results in a crash.
With Bazel, linking both the bigtable client and the storage client, results in a crash. I (@coryan) suspect it is the versions of OpenSSL: gRPC links BoringSSL, libcurl links the native OpenSSL.

/cc: @drethage

### PR DESCRIPTION
**Pull request by coryan**
This fixes #1087. It changes the Bazel builds to link all our dependencies
against the same SSL version (BoringSSL). It compiles libcurl from source,
which is consistent with out Bazel works in general, and forces libcurl to link
against the same BoringSSL version.

To reproduce the problem I created an example using both Cloud Bigtable
and Google Cloud Storage. I believe this example should be preserved because
it is useful in its own right.

When compiling against BoringSSL the implementation of base64 encoding and
decoding in the storage client is completely different, because BoringSSL has
retired some of the functions we needed (`BIO_f_base64()` for example).

---
This change is [Reviewable](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1088)

### CODE REVIEW

**Comment by coryan** [comment]
PTAL. This is ready for review now.

File: google/cloud/examples/gcs2cbt.cc [hunk 1]
```diff
@@ -0,0 +1,343 @@
...
+      } else if (0 == argument.find(key_option)) {
+        keys.push_back(std::stoi(argument.substr(key_option.size())) - 1);
+      } else if (0 == argument.find(keys_separator_option)) {
+        keys_separator = argument.substr(keys_separator_option.size());
+      } else {
+        return argument;
+      }
+    }
+    std::string cmd = argv[0];
+    auto last_slash = std::string(cmd).find_last_of('/');
```
Comment (houglum) [inline google/cloud/examples/gcs2cbt.cc]: I assume this is to reduce something like `/path/to/executable` to `executable`?  If so, this won't achieve the desired result on Windows where the pathname component separator is `\`.  (Non-issue if this doesn't even work for Windows - I have no context on the Bigtable stuff)
