### PR TITLE
Complete implementation of bigtable::TableAdmin

### LINKED ISSUE #79: Create a client library for the Admin API.
This is an umbrella issue.  It will need to be broken down into specific tasks.  We have it here so we can refer to it in documents and TODO entries.

### PR DESCRIPTION
**Pull request by coryan**
This fixes #79.  In this PR we introduced the remaining TableAdmin functions, and provide an integration test for the class.  There are missing integration tests for DropRows*, because their implementation would be overly complicated until #32 is done.  There is a separate issue (#141) to track this.

### CODE REVIEW

File: bigtable/tests/admin_test.cc [hunk 1]
```diff
@@ -0,0 +1,151 @@
...
+  auto get1 = admin.GetTable(table1, admin_proto::Table::FULL);
+  if (2 != get1.column_families_size()) {
+    std::string text;
+    google::protobuf::TextFormat::PrintToString(get1, &text);
+    std::ostringstream os;
+    os << "Unexpected result from GetTable(table1): " << text;
+    throw std::runtime_error(os.str());
+  }
+  std::cout << "GetTable(table1) successful" << std::endl;
+
```
Comment (carterpage) [inline bigtable/tests/admin_test.cc]: Do a paranoid check that ListTables now returns two tables, since you're about to check after delete that list returns 1 once again.

File: bigtable/tests/admin_test.cc [hunk 2]
```diff
@@ -0,0 +1,151 @@
...
+  table_list = admin.ListTables(admin_proto::Table::NAME_ONLY);
+  if (1UL != table_list.size()) {
+    throw std::runtime_error("Expected only one table after delete table0");
+  }
+  if (t1.name() != table_list[0].name()) {
+    throw std::runtime_error("Expected only table1 to survive");
+  }
+  std::cout << "ListTables() after DeleteTable() successful" << std::endl;
+
+  using GC = bigtable::GcRule;
```
Comment (carterpage) [inline bigtable/tests/admin_test.cc]: After all the state changes above, it takes too much effort to reason about the current state and how the below modification should change it.

Create a new table right above the ModifyColumnFamilies call to make it easier to see the before/after side-by-side.

File: bigtable/tests/admin_test.cc [hunk 3]
```diff
@@ -0,0 +1,151 @@
...
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+#include <google/protobuf/text_format.h>
+#include <google/protobuf/util/message_differencer.h>
+#include <sstream>
+#include "bigtable/admin/admin_client.h"
+#include "bigtable/admin/table_admin.h"
+
+int main(int argc, char* argv[]) try {
```
Comment (carterpage) [inline bigtable/tests/admin_test.cc]: This isn't super extensible as a one-method test. I'd suggest breaking it into two methods you invoke from main, first one testing create+get+delete operations, and the second testing column family modification.

It would be nice if there were a comment with simple description of the test. Even "Integration test to create and delete some tables" is sufficient.

File: bigtable/tests/run_integration_tests.sh [hunk 4]
```diff
@@ -63,3 +63,7 @@ echo
 echo "Running Table::Apply() integration test."
 # The project and instance do not matter for the Cloud Bigtable emulator.
 ./integration_test emulated emulated test-table
+
+echo
+echo "Running TableAdmin integration test."
+./admin_test emulated admin-tests
```
Comment (carterpage) [inline bigtable/tests/run_integration_tests.sh]: File names are confusing. They are both integration tests. Can we change them to data_integration_test and admin_integration_test or at least something consistent?

File: bigtable/admin/table_admin.cc [hunk 5]
```diff
@@ -78,11 +78,48 @@ std::vector<::google::bigtable::admin::v2::Table> TableAdmin::ListTables(
...
   request.set_view(view);
 
   auto error_message = absl::StrCat("GetTable(", request.name(), ")");
-  return CallWithRetry(&StubType::GetTable, request, std::move(error_message));
+  return CallWithRetry(&StubType::GetTable, request, error_message);
+}
+
+void TableAdmin::DeleteTable(std::string table_id) {
+  btproto::DeleteTableRequest request;
+  request.set_name(CreateTableName(table_id));
```
[the remark this answers is not in the document]
Comment (coryan) [reply bigtable/admin/table_admin.cc]: Fixed.

File: bigtable/admin/table_admin.h [hunk 6]
```diff
@@ -120,16 +121,70 @@ class TableAdmin {
...
+   * @param table_id the id of the table within the instance associated with
+   *     this object. The full name of the table is
+   *     `this->instance_name() + "/tables/" + table_id`
+   * @throws std::exception if the operation cannot be completed.
+   */
+  void DropAllRows(std::string table_id);
+
  private:
+  /// Compute the fully qualified instance name.
   std::string CreateInstanceName() const;
```
[the remark this answers is not in the document]
Comment (coryan) [reply bigtable/admin/table_admin.h]: Fixed.

File: bigtable/admin/table_admin.h [hunk 7]
```diff
@@ -120,16 +121,70 @@ class TableAdmin {
...
 
+  /// Return the fully qualified name of a table in this object's instance.
+  std::string CreateTableName(std::string const& table_id) const {
```
[the remark this answers is not in the document]
Comment (coryan) [reply bigtable/admin/table_admin.h]: Fixed.

File: bigtable/admin/table_admin_test.cc [hunk 8]
```diff
@@ -375,3 +375,105 @@ TEST_F(TableAdminTest, GetTableTooManyFailures) {
...
+  bigtable::TableAdmin tested(client_, "the-instance");
+  std::string expected_text = R"""(
+name: 'projects/the-project/instances/the-instance/tables/the-table'
+modifications {
+  id: 'foo'
+  create { gc_rule { max_age { seconds: 172800 }}}
+}
+modifications {
+  id: 'bar'
+  update { gc_rule { max_age { seconds: 172800 }}}
```
[the remark this answers is not in the document]
Comment (coryan) [reply bigtable/admin/table_admin_test.cc]: Done.

File: bigtable/tests/admin_test.cc (hunk 3 above)
Comment (coryan) [reply bigtable/tests/admin_test.cc]: Done.

File: bigtable/tests/admin_test.cc (hunk 1 above)
Comment (coryan) [reply bigtable/tests/admin_test.cc]: Done.

File: bigtable/tests/admin_test.cc (hunk 2 above)
Comment (coryan) [reply bigtable/tests/admin_test.cc]: Done.
At least I tried to make it easier to read, let me know if it needs further work.

File: bigtable/tests/run_integration_tests.sh (hunk 4 above)
Comment (coryan) [reply bigtable/tests/run_integration_tests.sh]: Done.

**Comment by coryan** [comment]
PTAL.
