### PR TITLE
Use non-throwing JSON parser for ObjectMetadata.

### LINKED ISSUE #1685: Fix CurlClient to use non-throw JSON parsing.
In a number of places CurlClient throws exceptions, or rather, it calls the json parser which raises exceptions on error.  We want to return a `Status` instead.

### PR DESCRIPTION
**Pull request by coryan**
This is the last PR in the series to use the non-throwing version of
nl::json::parse(). It fixes #1685.

---
This change is [Reviewable](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1745)

### CODE REVIEW

File: google/cloud/storage/client_notifications_test.cc [hunk 1]
```diff
@@ -178,7 +178,7 @@ TEST_F(NotificationsTest, GetNotification) {
   NotificationMetadata actual =
       client.GetNotification("test-bucket", "test-notification-1");
   EXPECT_EQ(expected, actual);
-}
+}  // namespace
```
Comment (devbww) [inline google/cloud/storage/client_notifications_test.cc]: New comment looks out of place.

File: google/cloud/storage/client_object_copy_test.cc [hunk 2]
```diff
@@ -63,7 +63,7 @@ TEST_F(ObjectCopyTest, CopyObject) {
   std::string text = R"""({
       "name": "test-bucket-name/test-object-name/1"
 })""";
```
Comment (devbww) [inline google/cloud/storage/client_object_copy_test.cc]: Is it important to not indent here (and line 133)?

File: google/cloud/storage/client_notifications_test.cc (hunk 1 above)
Comment (coryan) [reply google/cloud/storage/client_notifications_test.cc]: Indeed. Removed.

File: google/cloud/storage/client_object_copy_test.cc (hunk 2 above)
Comment (coryan) [reply google/cloud/storage/client_object_copy_test.cc]: No, these are JSON strings (embedded in C++ raw string literals), spaces are ignored. I have not convinced myself of which style is better for these. Well, I really like using the raw string literals, because JSON is full of double quotes (and braces!). But their internal indentation, and their indentation within the program I am not sure what is best, suggestions are welcome.

**Comment by coryan** [comment]
PTAL.

File: google/cloud/storage/client_object_copy_test.cc (hunk 2 above)
Comment (devbww) [reply google/cloud/storage/client_object_copy_test.cc]: If spaces are ignored, I think I prefer the indented version (clang-format seems to leave them alone).  But no big deal either way.  Consistency should probably be the only goal, and at the moment it looks like we have 60 occurrences without indentation and 45 with.
