### PR TITLE
Fix include rules for headers.

### LINKED ISSUE #1179: Fix install directory target for headers google/cloud/storage/CMakeLists.txt
It says `blah/blah/client` which is obviously wrong I think it works due to the top-level CMake installing all the headers, which may be its own problem too.

### PR DESCRIPTION
**Pull request by coryan**
This fixes #1179. Each library should only install its public headers.
Headers used for testing, benchmarks, and examples should not be
installed. The internal headers are more difficult, we should probably
install the minimum set that is used in the implementation of public
types, but that is too fine grained to easily support.

---
This change is [Reviewable](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1196)

### CODE REVIEW

File: ci/travis/build-docker.sh [hunk 1]
```diff
@@ -216,6 +216,27 @@ if [ "${TEST_INSTALL:-}" = "yes" ]; then
...
+      <(echo /var/tmp/staging/include/google/cloud ; \
+        echo /var/tmp/staging/include/google/cloud/bigtable ; \
+        echo /var/tmp/staging/include/google/cloud/bigtable/internal ; \
+        echo /var/tmp/staging/include/google/cloud/firestore ; \
+        echo /var/tmp/staging/include/google/cloud/internal ; \
+        echo /var/tmp/staging/include/google/cloud/storage ; \
+        echo /var/tmp/staging/include/google/cloud/storage/internal ; \
+        echo /var/tmp/staging/include/google/cloud/storage/oauth2 ; \
+        /bin/true) | grep -c /var/tmp; then
+      echo "${COLOR_YELLOW}Installed directories does not match expectation.${COLOR_RESET}"
```
Comment (houglum) [inline ci/travis/build-docker.sh]: s/does not/do not/
