### PR TITLE
Sample row keys

### LINKED ISSUE #209: Implement bigtable::Table::SampleRowKeys
Implement a version that reads the full streaming response and returns it as a collection, most likely a std::vector<>.

It is temping to use a iterator interface to return the response, as we do in `ReadRows()`, but that does not work because when we retry we need a consistent view of the samples, and must start from the beginning.

If it is possible to use any collection via `back_inserter` or via a `std::function()`, then why not?

### PR DESCRIPTION
**Pull request by paprat**
This PR is for SampleRowKeys Implementation(Sync). Fixes #209

### CODE REVIEW

File: bigtable/client/table.cc [hunk 1]
```diff
@@ -133,6 +133,47 @@ void Table::BulkApply(BulkMutation&& mut) {
...
+  // Build the RPC request for SampleRowKeys
+  btproto::SampleRowKeysRequest request;
+  btproto::SampleRowKeysResponse response;
+  request.set_table_name(table_name_);
+
+  while (true) {
+    grpc::ClientContext client_context;
+    backoff_policy->setup(client_context);
+    retry_policy->setup(client_context);
+
```
Comment (coryan) [inline bigtable/client/table.cc]: We recently introduced the `metadata_update_policy_`, please use .

File: bigtable/client/table.cc [hunk 2]
```diff
@@ -133,6 +133,47 @@ void Table::BulkApply(BulkMutation&& mut) {
...
+    auto stream = client_->Stub()->SampleRowKeys(&client_context, request);
+    while (stream->Read(&response)) {
+      // Assuming collection will be either list or vector.
+      Table::RowKeySample row_sample;
+      row_sample.offset_bytes = response.offset_bytes();
+      row_sample.row_key = response.row_key();
```
Comment (coryan) [inline bigtable/client/table.cc]: can we move the `row_key()` contents from `response` into `row_sample` to avoid copying the string?

File: bigtable/client/table.cc (hunk 1 above)
Comment (coryan) [inline bigtable/client/table.cc]: We recently introduced `metadata_update_policy_`, please use it here to update the request metadata.

File: bigtable/client/table.cc [hunk 3]
```diff
@@ -133,6 +133,47 @@ void Table::BulkApply(BulkMutation&& mut) {
...
+      inserter(row_sample);
```
Comment (coryan) [inline bigtable/client/table.cc]: I think `inserter(std::move(row_sample));` avoids a copy.

File: bigtable/client/table.h [hunk 4]
```diff
@@ -60,6 +60,14 @@ inline std::string TableName(std::shared_ptr<DataClient> client,
  */
 class Table {
  public:
+  /**
+   *
```
Comment (coryan) [inline bigtable/client/table.h]: Please add documentation, e.g.:

```C++
/// A simple wrapper to represent the response from `Table::SampleRowKeys()`.
```

File: bigtable/client/table.h [hunk 5]
```diff
@@ -277,7 +301,14 @@ class Table {
   Row CallReadModifyWriteRowRequest(
       ::google::bigtable::v2::ReadModifyWriteRowRequest request);
 
- private:
+  /**
+   * Wrapper function so that .cc doesn't need to know of template type.
+   * @param inserter Function to insert the object to result.
```
Comment (coryan) [inline bigtable/client/table.h]: Insert an empty comment line here:

```C++
 *
 * @param ...
```

File: bigtable/client/table_sample_row_keys_test.cc [hunk 6]
```diff
@@ -0,0 +1,188 @@
+// Copyright 2017 Google Inc.
```
Comment (coryan) [inline bigtable/client/table_sample_row_keys_test.cc]: s/2017/2018/

File: bigtable/client/table.h [hunk 7]
```diff
@@ -224,6 +230,24 @@ class Table {
                          std::vector<Mutation> true_mutations,
                          std::vector<Mutation> false_mutations);
 
+  /**
+   * Return a sample of the row keys in the table, including approximate data
+   * sizes.
+   *
+   * @return a collection of SampleRowKeys. (The type of collection is specified
```
Comment (coryan) [inline bigtable/client/table.h]: Remove the parenthesis.  You can just say:

```C++
/**
  * Sample of the row keys in the table, including approximate data sizes.
  *
  * The application can specify the collection type, for example:
  * @code
  * auto as_vector = table.SampleRows<std::vector>();
  * auto as_list = table.SampleRows<std::list>();
  * @endcode
  */
```

File: bigtable/client/table.h [hunk 8]
```diff
@@ -224,6 +230,24 @@ class Table {
...
+   * by the user(vector or list).
+   */
+  template <template <typename...> class Collection>
+  Collection<Table::RowKeySample> sample_rows() {
```
Comment (coryan) [inline bigtable/client/table.h]: Sorry I did not notice this before, we settled on CamelCase naming after the design doc was written.  This should be `SampleRows()`.

File: bigtable/client/table.h [hunk 9]
```diff
@@ -224,6 +230,24 @@ class Table {
...
+    Collection<Table::RowKeySample> result;
+    sample_rows_impl(
```
Comment (coryan) [inline bigtable/client/table.h]: Same here, should be `SampleRowsImpl()`.

File: bigtable/client/table.h (hunk 7 above)
Comment (paprat) [reply bigtable/client/table.h]: Done.

File: bigtable/client/table.h (hunk 8 above)
Comment (paprat) [reply bigtable/client/table.h]: Done.

File: bigtable/client/table.h (hunk 9 above)
Comment (paprat) [reply bigtable/client/table.h]: Done.
