### PR TITLE
Wrap grpc status with exception

### LINKED ISSUE #119: Create std::exception that wraps a grpc::Status
The application may want to examine the `grpc::Status` in all its glory.

### PR DESCRIPTION
**Pull request by coryan**
This fixes #119.  Instead of raising a plain `std::runtime_error`
exception with the information in the `what()` string the
library now raises `bigtble::GRpcError` with the relevant
`grpc::Status` fields (error code, error message, and error details).
The class is derived from `std::runtime_error` because that is
the exception that one should use to, well, represent run-time
errors, which these are.

### CODE REVIEW

File: bigtable/client/internal/throw_delegate.cc [hunk 1]
```diff
@@ -69,12 +65,14 @@ namespace internal {
...
-     << status.error_message() << " [" << status.error_code() << "] "
-     << status.error_details();
-  internal::RaiseRuntimeError(os.str());
+#ifdef GOOGLE_CLOUD_CPP_HAVE_EXCEPTIONS
+  throw bigtable::GRpcError(msg, status);
+#else
+  bigtable::GRpcError ex(msg, status);
+  std::cerr << "Aborting because exceptions are disabled: " << ex.what()
+            << std::endl;
+  std::abort();
```
Comment (deepankarsharma) [inline bigtable/client/internal/throw_delegate.cc]: 1. Could you clarify the error handling strategy here from a users point of view?
2. In the exceptions case will the exception be raised all the way to the user, or will we catch it and do the appropriate thing in the bigtable client codebase?
3. What do we expect the user to do in the no exceptions case?

File: bigtable/client/grpc_error.h [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+  std::string const& error_details() const { return error_details_; }
+  //@}
+
+ private:
+  /// Return the what() string given @p status.
+  static std::string CreateWhatString(char const* what,
+                                      grpc::Status const& status);
+
+ private:
+  grpc::StatusCode error_code_;
```
Comment (deepankarsharma) [inline bigtable/client/grpc_error.h]: In case this exception will reach users drop usage of grpc::StatusCode and change name away from GRpcError.

File: bigtable/client/internal/throw_delegate.cc (hunk 1 above)
Comment (coryan) [reply bigtable/client/internal/throw_delegate.cc]: The exceptions are raised all the way to the user.  If the user compiled without exceptions the error "handling" is we abort.  If the user is called "Google" there is an internal API to catch (most) errors without exceptions.  This pending PR has more context:

https://github.com/GoogleCloudPlatform/google-cloud-cpp/pull/98/files

File: bigtable/client/grpc_error.h (hunk 2 above)
Comment (coryan) [reply bigtable/client/grpc_error.h]: Why?  The error represents a run-time problem, reported by gRPC, that stops the library from completing its work.  Is not like we want (or could if we wanted to) hide the fact that gRPC is the underlying RPC mechanism.

**Comment by coryan** [comment]
Let me know if those answers make sense.  Happy to discuss in person if the github reviews do not provide enough bandwidth.

**Comment by coryan** [comment]
Per our offline discussion, I updated the documentation and created a bug for that idea around making the call to `std::abort()` configurable.  PTAL.
