### PR TITLE
Fix EnvironmentVariableRestore helper.

### LINKED ISSUE #796: Troubleshoot flaky test in google/cloud/storage
This test fails sometimes:

```
60/75 Test #60: internal_google_application_default_credentials_file_test ...***Exception: Exit code 0xc0000409
  0.19 sec
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from DefaultServiceAccountFileTest
[ RUN      ] DefaultServiceAccountFileTest.EnvironmentVariableSet
[       OK ] DefaultServiceAccountFileTest.EnvironmentVariableSet (0 ms)
[ RUN      ] DefaultServiceAccountFileTest.HomeSet
[       OK ] DefaultServiceAccountFileTest.HomeSet (1 ms)
[ RUN      ] DefaultServiceAccountFileTest.HomeNotSet
minkernel\crts\ucrt\inc\corecrt_internal_string_templates.h(81) : Assertion failed: (L"Buffer is too small" && 0)
      Start 61: internal_insert_object_media_request_test
61/75 Test #61: internal_insert_object_media_request_test ...................   Passed    0.08 sec
      Start 62: internal_list_objects_request_test
```

### PR DESCRIPTION
**Pull request by coryan**
Change the `previous_` member variable to `std::string` so we copy
the value returned by `std::getenv()`. On Windows the pointer returned
by `std::getenv()` is not guaranteed to remain valid after modifying
*other* environment variables, thus the need for this copy.

This fixes #796.

Also always use GoogleApplicationDefaultCredentailsHomeVariable to
fetch the HOME (vs APPDATA) variable name.  This was a bit
of cleanup I did while trying to figure out what was broken.

### CODE REVIEW

File: google/cloud/storage/internal/google_application_default_credentials_file.cc [hunk 1]
```diff
@@ -51,11 +51,12 @@ std::string GoogleApplicationDefaultCredentialsFile() {
   }
   // There are probably more efficient ways to do this, but meh, the strings
   // are typically short, and this does not happen that often.
-  auto root = std::getenv(CREDENTIALS_HOME_VAR);
+  auto root = std::getenv(GoogleApplicationDefaultCredentialsHomeVariable());
```
Comment (mfschwartz) [inline google/cloud/storage/internal/google_application_default_credentials_file.cc]: The CL description said you changed the code to make a copy of the char*  returned by getenv but I don't see a copy being made here?

Comment (coryan) [reply google/cloud/storage/internal/google_application_default_credentials_file.cc]: The `previous_` member variable is now a `std::string` (was a `char const*`), so assigning to it makes a copy, right?

**Comment by coryan** [comment]
I updated the comment to explain this better.  PTAL.

File: google/cloud/storage/internal/google_application_default_credentials_file.cc (hunk 1 above)
Comment (mfschwartz) [reply google/cloud/storage/internal/google_application_default_credentials_file.cc]: Thanks, I missed that.
