### PR TITLE
Complete integration tests for bigtable::Filter

### LINKED ISSUE #84: Decide what is the right behavior when creating "invalid" filters.
Some of the functions to create filters can produce non-sensical filters, for example, you can call `bigtable::Filter::Latest(-1)`.  Most likely that fails on the server side (does it? the proto documentation does not say), so maybe we should check in the client side and raise an exception.

One could argue that it is Okay though, the function did as requested, it is beyond's the client library's ability to check if your filters are semantically sensible.

Even if we decide to allow such filters to be created, we should document the effect of setting up filters with strange values.

This is a dependency for #30.

### PR DESCRIPTION
**Pull request by coryan**
This fixes #150, it completes the implementation of the integration tests for `bigtable::Filter`.  Incidentally, it also fixes #84.  All the filters have documented behaviors on invalid inputs.

### CODE REVIEW

**Comment by coryan** [comment]
Ping.

File: bigtable/client/filters.h [hunk 1]
```diff
@@ -85,9 +85,13 @@ class Filter {
    * Return a filter that matches column families matching the given regexp.
    *
    * @param pattern the regular expression.  It must be a valid
-   *     [RE2](https://github.com/google/re2/wiki/Syntax) pattern.
-   *     For technical reasons, the regex must not contain the ':' character,
-   *     even if it is not being used as a literal.
+   *     [RE2](https://github.com/google/re2/wiki/Syntax) pattern.  For
+   *     technical reasons, the regex must not contain the ':' character, even
+   *     if it is not being used as a literal. The server rejects filters with
+   *     an invalid patterns, including patterns containing the ':' character.
```
Comment (mbrukman) [inline bigtable/client/filters.h]: s/an //
