### PR TITLE
Document the order of cells within a row.

### LINKED ISSUE #82: Document order of cells returned by ReadRows() within a row.
I cannot find clear documentation of what the "first N" RowFilter actually would skip.  The documentation most likely exist, I just cannot find it.

Obvious it is the first N cells, but what is the order of the cells within a row?  The natural assumption is that cells are returned in the order defined by the column families, and then the column qualifiers within a column family, and then the timestamps within each column.  That is probably true, but I cannot find any docs saying that and it is better if I document that assumption.

This issue is here to find the right documentation (it must exist I just could not find it), link it from here and then update the documentation for the `bigtable::Filter` creation functions if the assumptions I made were wrong.

### PR DESCRIPTION
**Pull request by coryan**
Such as it is (the order is not guaranteed for column families).
This fixes #82.

### CODE REVIEW

File: bigtable/client/filters.h [hunk 1]
```diff
@@ -200,10 +200,13 @@ class Filter {
    * of multiple filters via the Union() function (aka Interleaved in the
    * proto).  Furthermore, notice that this is the cells within a row, if there
    * are multiple column families and columns, the cells are returned ordered
-   * by first column family, and then by column qualifier, and then by
-   * timestamp.
+   * by:
+   * - The column family internal ID, which is not necessarily the
+   *   lexicographical order of the column family names.  Also, the ID of each
+   *   column family may change on each row.
```
Comment (garye) [inline bigtable/client/filters.h]: I'm not quite sure how to parse this. Is there a way to rephrase? Overall the description seems accurate, though.

**Comment by coryan** [comment]
PTAL.

File: bigtable/client/filters.h [hunk 2]
```diff
@@ -196,16 +196,16 @@ class Filter {
...
-   *   lexicographical order of the column family names.  Also, the ID of each
-   *   column family may change on each row.
-   * - The column names, lexicographically.
-   * - Timestamp in reverse order.
+   * Note that cells might be repeated, such as when interleaving the results
+   * of multiple filters via the `Interleave()` function.  Furthermore, this
+   * filter apples to the cells within a row, if there are multiple column
+   * families and/or columns in a row the order is:
+   * - All the cells for a column family appear together, but there is no
+   *   guarantee on the order of the column families.  Furthermore, column
```
Comment (carterpage) [inline bigtable/client/filters.h]: I like this much better. References to "internal ID" make me cringe. :-)

File: bigtable/client/filters.h [hunk 3]
```diff
@@ -196,14 +196,17 @@ class Filter {
...
-   * are multiple column families and columns, the cells are returned ordered
-   * by first column family, and then by column qualifier, and then by
-   * timestamp.
-   *
-   * TODO(#82) - check the documentation around ordering of columns.
+   * Note that cells might be repeated, such as when interleaving the results
+   * of multiple filters via the `Interleave()` function.  Furthermore, this
+   * filter apples to the cells within a row, if there are multiple column
+   * families and/or columns in a row the order is:
+   * - All the cells for a column family appear together, but there is no
```
Comment (mbrukman) [inline bigtable/client/filters.h]: Have you checked the rendering of this in Doxygen output? Doxygen supports Markdown, but most Markdown parsers I've seen require adding a blank line before a bulleted list; otherwise, it doesn't render properly.

File: bigtable/client/filters.h [hunk 4]
```diff
@@ -215,17 +218,17 @@ class Filter {
...
-   *   lexicographical order of the column family names.
-   * - The column names, lexicographically.
-   * - Timestamp in reverse order.
-   *
-   * TODO(#82) - check the documentation around ordering of columns.
+   * Note that cells might be repeated, such as when interleaving the results
+   * of multiple filters via the `Interleave()` function.  Furthermore, this
+   * filter apples to the cells within a row, if there are multiple column
+   * families and/or columns in a row the order is:
+   * - All the cells for a column family appear together, but there is no
```
Comment (mbrukman) [inline bigtable/client/filters.h]: Same comment about rendering as above.

Comment (coryan) [reply bigtable/client/filters.h]: I did, it works.  Look at the attached file:

[filter-doxygen-render.pdf](https://github.com/GoogleCloudPlatform/google-cloud-cpp/files/1591934/filter-doxygen-render.pdf)

File: bigtable/client/filters.h (hunk 2 above)
Comment (coryan) [reply bigtable/client/filters.h]: Certainly.

File: bigtable/client/filters.h (hunk 3 above)
Comment (coryan) [reply bigtable/client/filters.h]: Yes, see below.

**Comment by coryan** [comment]
PTAL.

File: bigtable/client/filters.h (hunk 4 above)
Comment (mbrukman) [reply bigtable/client/filters.h]: Perfect, thanks!

File: bigtable/client/filters.h (hunk 3 above)
Comment (mbrukman) [reply bigtable/client/filters.h]: LGTM, thanks for checking.

File: bigtable/client/filters.h [hunk 5]
```diff
@@ -215,17 +218,17 @@ class Filter {
...
+   *   guarantee on the order of the column families.  Furthermore, column
+   *   families may appear in different orders in different rows.
+   * - Within a column family the cells are ordered by column name, column names
```
Comment (mbrukman) [inline bigtable/client/filters.h]: - Within a column family, the cells are ordered by column name, where column names are sorted lexicographically.

File: bigtable/client/filters.h [hunk 6]
```diff
@@ -215,17 +218,17 @@ class Filter {
...
+   *   are compared lexicographically.
+   * - With a column, the cells appear in descending order by timestamp.
```
Comment (mbrukman) [inline bigtable/client/filters.h]: s/With/Within/

File: bigtable/client/filters.h [hunk 7]
```diff
@@ -196,14 +196,17 @@ class Filter {
...
```
Comment (mbrukman) [inline bigtable/client/filters.h]: s/With/Within/

File: bigtable/client/filters.h [hunk 8]
```diff
@@ -196,14 +196,17 @@ class Filter {
...
-   * of multiple filters via the Union() function (aka Interleaved in the
-   * proto).  Furthermore, notice that this is the cells within a row, if there
-   * are multiple column families and columns, the cells are returned ordered
-   * by first column family, and then by column qualifier, and then by
-   * timestamp.
-   *
-   * TODO(#82) - check the documentation around ordering of columns.
+   * Note that cells might be repeated, such as when interleaving the results
+   * of multiple filters via the `Interleave()` function.  Furthermore, this
+   * filter apples to the cells within a row, if there are multiple column
```
Comment (mbrukman) [inline bigtable/client/filters.h]: s/row, if/row; if/

File: bigtable/client/filters.h [hunk 9]
```diff
@@ -196,14 +196,17 @@ class Filter {
...
+   * families and/or columns in a row the order is:
```
Comment (mbrukman) [inline bigtable/client/filters.h]: s/row the/row, the/

File: bigtable/client/filters.h [hunk 10]
```diff
@@ -196,14 +196,17 @@ class Filter {
...
+   * - All the cells for a column family appear together, but there is no
+   *   guarantee on the order of the column families.  Furthermore, column
+   *   families may appear in different orders in different rows.
+   * - Within a column family the cells are ordered by column name, column names
```
Comment (mbrukman) [inline bigtable/client/filters.h]: - Within a column family, the cells are ordered by column name, where column names are sorted lexicographically.

File: bigtable/client/filters.h [hunk 11]
```diff
@@ -215,17 +218,17 @@ class Filter {
...
-   * by:
-   * - The column family internal ID, which is not necessarily the
-   *   lexicographical order of the column family names.
-   * - The column names, lexicographically.
-   * - Timestamp in reverse order.
-   *
-   * TODO(#82) - check the documentation around ordering of columns.
+   * Note that cells might be repeated, such as when interleaving the results
+   * of multiple filters via the `Interleave()` function.  Furthermore, this
+   * filter apples to the cells within a row, if there are multiple column
```
Comment (mbrukman) [inline bigtable/client/filters.h]: s/row, if/row; if/

File: bigtable/client/filters.h [hunk 12]
```diff
@@ -215,17 +218,17 @@ class Filter {
...
+   * families and/or columns in a row the order is:
```
Comment (mbrukman) [inline bigtable/client/filters.h]: s/row the/row, the/

File: bigtable/client/filters.h (hunk 8 above)
Comment (coryan) [reply bigtable/client/filters.h]: Fixed.

File: bigtable/client/filters.h (hunk 9 above)
Comment (coryan) [reply bigtable/client/filters.h]: Fixed.

File: bigtable/client/filters.h (hunk 10 above)
Comment (coryan) [reply bigtable/client/filters.h]: Thanks!

File: bigtable/client/filters.h (hunk 7 above)
Comment (coryan) [reply bigtable/client/filters.h]: Fixed.

File: bigtable/client/filters.h (hunk 11 above)
Comment (coryan) [reply bigtable/client/filters.h]: Fixed, this is identical to the previous comment, so I just copied it.

**Comment by coryan** [comment]
PTAL.
I did not skip the ci build because Doxygen, though I expect no breakage.

File: bigtable/client/filters.h (hunk 6 above)
Comment (coryan) [reply bigtable/client/filters.h]: Fixed.

File: bigtable/client/filters.h (hunk 5 above)
Comment (coryan) [reply bigtable/client/filters.h]: Fixed.

File: bigtable/client/filters.h (hunk 12 above)
Comment (coryan) [reply bigtable/client/filters.h]: Fixed.

File: bigtable/client/filters.h (hunk 10 above)
Comment (coryan) [reply bigtable/client/filters.h]: Fixed.
